### ISSUE TITLE
[$30] When we switch to the Topcoder X tab for the already created challenge; some data is missing 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tcx-azure-devops-ext#57] opened 2020-11-13 04:13 UTC
![image](https://user-images.githubusercontent.com/42398485/99027981-9f201700-2594-11eb-94fc-abb56f00b3f9.png)

![image](https://user-images.githubusercontent.com/42398485/99027988-a47d6180-2594-11eb-907b-5daac9becb33.png)

### Steps to reproduce the problem

1. Deploy the app and create the initial setup
2. Open Board -> Work items.
3. Open or create a work item (Issue).
4. Fill the details (Description etc)
5. Switch to Topcoder X
6. Select the project, Title, Public and private description and prize
7. Click Save
8. Click Send to Topcoder
9. Check the challenge page opens - https://www.topcoder-dev.com/challenges/1e7c87dd-569e-4ee7-8e23-ccb24ca888e5
10. Click on the Issue from Work Item
11. Then switch to Topcoder-X and check

 ### Actual behavior
- When we switch to the Topcoder X tan for the already created challenge; some data is missing 

### Expected behavior
- Should display the data
 
 
#### Environment
**- OS:** 10
**- Device (w/version):** Laptop, Windows 10 
**- Browser** 86.0.4240.183

**Comment by jmgasper** [comment] 2020-11-18 00:41
Contest https://www.topcoder.com/challenges/30151817 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-11-18 02:51
Contest https://www.topcoder.com/challenges/30151817 has been updated - it has been assigned to dhruvit_r.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by dhruvit-r** [comment] 2020-11-24 19:52
@jmgasper Not able to reproduce this. I need to know if this intermittent. If not, this has probably been fixed already.

**Comment by dhruvit-r** [comment] 2020-12-01 18:16
@jmgasper 👆

**Comment by jmgasper** [comment] 2020-12-01 22:24
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed by jmgasper** 2020-12-01 22:24 UTC
Labels: Accepted, tcx_Assigned, tcx_ReadyForReview
